from .utilitarios import *
from .home import *
from .professores import *
from .alunos import *
from .faltas import *
from .relatorios import *
from .laboratorios import *
from .whatsapp import *
from .avisos_professores import *
