# Generated by Django 5.2.13 on 2026-04-28 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0020_registroocorrenciaaluno_resposta_disparo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registroocorrenciaaluno",
            constraint=models.UniqueConstraint(
                fields=("aluno", "data", "tipo_ocorrencia"),
                name="unico_registro_por_aluno_data_tipo",
            ),
        ),
    ]
