# Generated by Django 6.0.4 on 2026-05-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_registroocorrenciaaluno_unico_registro_por_aluno_data_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofaltaaluno',
            name='pedagoga',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
