# Generated by Django 6.0.4 on 2026-05-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_registrofaltaaluno_pedagoga'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofaltaaluno',
            name='data_justificativa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrofaltaaluno',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrofaltaaluno',
            name='responsavel_justificativa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
