# Generated by Django 6.0.4 on 2026-05-10 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_registrofaltaaluno_data_justificativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_nome', models.CharField(max_length=150)),
                ('disciplina', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('ATESTADO', 'Atestado'), ('FALTA', 'Falta'), ('ATRASO', 'Atraso')], max_length=20)),
                ('quantidade_dias_atestado', models.PositiveIntegerField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visualizado', models.BooleanField(default=False)),
                ('visualizado_em', models.DateTimeField(blank=True, null=True)),
                ('visualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_professores_visualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso de Professor',
                'verbose_name_plural': 'Avisos de Professores',
                'ordering': ['-criado_em'],
            },
        ),
    ]
